name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - name: Checout Code
      uses: actions/checkout@v4
    - name: Install Node
      uses: actions/setup-node@v4
      with:
        node-version: 20
  
    - name: Run Tests
      run: npm test
